# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojos',
            new_name='dojo',
        ),
    ]
