# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-26 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoninjas', '0002_auto_20170926_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='thisisadesc', max_length=255),
            preserve_default=False,
        ),
    ]
